added massdrop/qmk_firmware feature/riot_xap branch changes 385262e

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -18,7 +18,7 @@ jobs:
     - name: Disable safe.directory check
       run : git config --global --add safe.directory '*'
 
-    - uses: actions/checkout@v4
+    - uses: actions/checkout@v3
       with:
         fetch-depth: 0
 
@@ -27,9 +27,7 @@ jobs:
 
     - name: Get changed files
       id: file_changes
-      uses: tj-actions/changed-files@v46
-      with:
-        use_rest_api: true
+      uses: tj-actions/changed-files@v35
 
     - name: Print info
       run: |
@@ -38,7 +36,6 @@ jobs:
         echo '${{ steps.file_changes.outputs.all_changed_files}}'
 
     - name: Run qmk lint
-      if: always()
       shell: 'bash {0}'
       run: |
         QMK_CHANGES=$(echo -e '${{ steps.file_changes.outputs.all_changed_files}}' | sed 's/ /\n/g')
@@ -64,12 +61,10 @@ jobs:
 
         qmk format-text ${{ steps.file_changes.outputs.all_changed_files}} || true
         for file in ${{ steps.file_changes.outputs.all_changed_files}}; do
-          if [[ -f $file ]]; then
-            if ! git diff --quiet $file; then
-              echo "File '${file}' Requires Formatting"
-              echo "::error file=${file}::Requires Formatting"
-              exit_code=$(($exit_code + 1))
-            fi
+          if ! git diff --quiet $file; then
+            echo "File '${file}' Requires Formatting"
+            echo "::error file=${file}::Requires Formatting"
+            exit_code=$(($exit_code + 1))
           fi
         done
 
@@ -77,11 +72,3 @@ jobs:
             exit 255
         fi
         exit $exit_code
-
-    - name: Verify keyboard aliases
-      if: always()
-      shell: 'bash {0}'
-      run: |
-        git reset --hard
-        git clean -xfd
-        qmk ci-validate-aliases
